<a href="https://colab.research.google.com/github/rlarjsdn4505/first-repository/blob/master/%EC%A1%B0%ED%98%84%EC%9A%B0%205%EB%B2%88%20%EA%B0%80%EC%84%A4(%EC%99%84%EC%84%B1_%EB%8D%B0%EC%9D%B4%ED%84%B0).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
font_path = '/content/NanumGothic.ttf'
print('exists:', os.path.exists(font_path), 'cwd:', os.getcwd())

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import font_manager as fm

fm._load_fontmanager(try_read_cache=False)

fm.fontManager.addfont(font_path)
prop = fm.FontProperties(fname=font_path)
family_name = prop.get_name()
print('detected family:', family_name)
mpl.rcParams['font.family'] = family_name
mpl.rcParams['axes.unicode_minus'] = False

exists: True cwd: /content
detected family: NanumGothic


In [ ]:
import pandas as pd

df1 = pd.read_csv('df1.csv')
df2 = pd.read_csv('df2.csv')

df = pd.merge(
    df1,
    df2,
    how='left',
    on='리뷰ID'
)


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85802 entries, 0 to 85801
Data columns (total 21 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   주문ID       85802 non-null  object 
 1   리뷰ID       85802 non-null  object 
 2   리뷰점수       85802 non-null  int64  
 3   리뷰작성일      85802 non-null  object 
 4   주문상태       85802 non-null  object 
 5   구매일시       85802 non-null  object 
 6   실제배송일      85802 non-null  object 
 7   예상배송일      85802 non-null  object 
 8   고객고유ID     85802 non-null  object 
 9   고객우편번호앞자리  85802 non-null  int64  
 10  고객도시       85802 non-null  object 
 11  고객주        85802 non-null  object 
 12  주문개수       85802 non-null  int64  
 13  상품가격합계     85802 non-null  float64
 14  배송비합계      85802 non-null  float64
 15  상품카테고리     85802 non-null  object 
 16  결제금액(주문합)  85802 non-null  float64
 17  총결제금액      85802 non-null  float64
 18  배송지연일수     85802 non-null  int64  
 19  배송지연여부     85802 non-null  int64  
 20  리뷰내용  

In [ ]:
df.head()

주문ID                              리뷰ID  리뷰점수  \
0  00010242fe8c5a6d1ba2dd792cb16214  97ca439bc427b48bc1cd7177abe71365     5   
1  00018f77f2f0320c557190d7a144bdd3  7b07bacd811c4117b742569b04ce3580     4   
2  000229ec398224ef6ca0657da4fc703e  0c5b33dea94867d1ac402749e5438e8b     5   
3  00024acbcdf0a6daa1e931b038114c75  f4028d019cb58564807486a6aaf33817     4   
4  00042b26cf59d7ce69dfabb4e55b4fd9  940144190dcba6351888cafa43f3a3a5     5   

                 리뷰작성일       주문상태                 구매일시                실제배송일  \
0  2017-09-21 00:00:00  delivered  2017-09-13 08:59:02  2017-09-20 23:43:48   
1  2017-05-13 00:00:00  delivered  2017-04-26 10:53:06  2017-05-12 16:04:24   
2  2018-01-23 00:00:00  delivered  2018-01-14 14:33:31  2018-01-22 13:19:16   
3  2018-08-15 00:00:00  delivered  2018-08-08 10:00:35  2018-08-14 13:32:39   
4  2017-03-02 00:00:00  delivered  2017-02-04 13:57:51  2017-03-01 16:42:31   

        예상배송일                            고객고유ID  고객우편번호앞자리  \
0  2017-09-29  871766c5855e863f6eccc05f988b23cb      28013   
1  2017-05-15  eb28e67c4c0b83846050ddfb8a35d051      15775   
2  2018-02-05  3818d81c6709e39d06b2738a8d3a2474      35661   
3  2018-08-20  af861d436cfc08b2c2ddefd0ba074622      12952   
4  2017-03-17  64b576fb70d441e8f1b2d7d446e483c5      13226   

                    고객도시 고객주  주문개수  상품가격합계  배송비합계        상품카테고리  결제금액(주문합)  \
0  campos dos goytacazes  RJ     1   58.90  13.29  문화/취미/엔터테인먼트      72.19   
1        santa fe do sul  SP     1  239.90  19.93          반려동물     259.83   
2          para de minas  MG     1  199.00  17.87   가구/홈리빙/인테리어     216.87   
3                atibaia  SP     1   12.99  12.79         뷰티/헬스      25.78   
4        varzea paulista  SP     1  199.90  18.14   가구/홈리빙/인테리어     218.04   

    총결제금액  배송지연일수  배송지연여부                                               리뷰내용  
0   72.19       8       0     Perfeito, produto entregue antes do combinado.  
1  259.83       2       0                                                NaN  
2  216.87      13       0  Chegou antes do prazo previsto e o produto sur...  
3   25.78       5       0                                                NaN  
4  218.04      15       0            Gostei pois veio no prazo determinado .

In [ ]:
df['고객도시'].nunique()

3887

In [ ]:
df['고객주'].nunique()

27

In [ ]:
df['주문ID'].nunique()

82548

In [ ]:
df['리뷰ID'].nunique()

82339

In [ ]:
df['주문상태'].nunique()

2

In [ ]:
df['고객고유ID'].nunique()

80489

In [ ]:
df['구매일시'] = pd.to_datetime(df['구매일시'])
df['실제배송일'] = pd.to_datetime(df['실제배송일'])
df['예상배송일'] = pd.to_datetime(df['예상배송일'])

# datetiem 컬럼 전처리
df['예상_소요일수'] = (df['예상배송일'] - df['구매일시']).dt.days
df['실제_소요일수'] = (df['실제배송일'] - df['구매일시']).dt.days
df['예상대비_지연일수'] = (df['실제배송일'] - df['예상배송일']).dt.days
df['예상대비_지연여부'] = (df['예상대비_지연일수'] > 0).astype(int)

# 리뷰 작성일 처리 (상품을 받은 뒤 리뷰 작성까지 걸린 시간)
df['리뷰작성일'] = pd.to_datetime(df['리뷰작성일'])
df['리뷰_작성지연일수'] = (df['리뷰작성일'] - df['실제배송일']).dt.days

# 리뷰 내용 여부 컬럼 / 리뷰_길이 컬럼 생성
df['리뷰내용여부'] = df['리뷰내용'].notna().astype(int)
df["리뷰_길이"] = df["리뷰내용"].fillna("").apply(len)

# 나머지 삭제
df = df.drop(columns = ['예상배송일', '실제배송일', '리뷰작성일', '배송지연일수', '배송지연여부', '리뷰내용'])


pd.set_option('display.max_columns', None)
df.head()

주문ID                              리뷰ID  리뷰점수  \
0  00010242fe8c5a6d1ba2dd792cb16214  97ca439bc427b48bc1cd7177abe71365     5   
1  00018f77f2f0320c557190d7a144bdd3  7b07bacd811c4117b742569b04ce3580     4   
2  000229ec398224ef6ca0657da4fc703e  0c5b33dea94867d1ac402749e5438e8b     5   
3  00024acbcdf0a6daa1e931b038114c75  f4028d019cb58564807486a6aaf33817     4   
4  00042b26cf59d7ce69dfabb4e55b4fd9  940144190dcba6351888cafa43f3a3a5     5   

        주문상태                구매일시                            고객고유ID  고객우편번호앞자리  \
0  delivered 2017-09-13 08:59:02  871766c5855e863f6eccc05f988b23cb      28013   
1  delivered 2017-04-26 10:53:06  eb28e67c4c0b83846050ddfb8a35d051      15775   
2  delivered 2018-01-14 14:33:31  3818d81c6709e39d06b2738a8d3a2474      35661   
3  delivered 2018-08-08 10:00:35  af861d436cfc08b2c2ddefd0ba074622      12952   
4  delivered 2017-02-04 13:57:51  64b576fb70d441e8f1b2d7d446e483c5      13226   

                    고객도시 고객주  주문개수  상품가격합계  배송비합계        상품카테고리  결제금액(주문합)  \
0  campos dos goytacazes  RJ     1   58.90  13.29  문화/취미/엔터테인먼트      72.19   
1        santa fe do sul  SP     1  239.90  19.93          반려동물     259.83   
2          para de minas  MG     1  199.00  17.87   가구/홈리빙/인테리어     216.87   
3                atibaia  SP     1   12.99  12.79         뷰티/헬스      25.78   
4        varzea paulista  SP     1  199.90  18.14   가구/홈리빙/인테리어     218.04   

    총결제금액  예상_소요일수  실제_소요일수  예상대비_지연일수  예상대비_지연여부  리뷰_작성지연일수  리뷰내용여부  리뷰_길이  
0   72.19       15        7         -9          0          0       1     46  
1  259.83       18       16         -3          0          0       0      0  
2  216.87       21        7        -14          0          0       1     90  
3   25.78       11        6         -6          0          0       0      0  
4  218.04       40       25        -16          0          0       1     39

In [ ]:
df['고객우편번호앞자리'].nunique()

14318

In [ ]:
df = df.drop(columns = ['주문ID', '리뷰ID', '고객고유ID','고객도시', '구매일시', '고객우편번호앞자리','결제금액(주문합)'], axis = 1)
df.head()

리뷰점수       주문상태 고객주  주문개수  상품가격합계  배송비합계        상품카테고리   총결제금액  예상_소요일수  \
0     5  delivered  RJ     1   58.90  13.29  문화/취미/엔터테인먼트   72.19       15   
1     4  delivered  SP     1  239.90  19.93          반려동물  259.83       18   
2     5  delivered  MG     1  199.00  17.87   가구/홈리빙/인테리어  216.87       21   
3     4  delivered  SP     1   12.99  12.79         뷰티/헬스   25.78       11   
4     5  delivered  SP     1  199.90  18.14   가구/홈리빙/인테리어  218.04       40   

   실제_소요일수  예상대비_지연일수  예상대비_지연여부  리뷰_작성지연일수  리뷰내용여부  리뷰_길이  
0        7         -9          0          0       1     46  
1       16         -3          0          0       0      0  
2        7        -14          0          0       1     90  
3        6         -6          0          0       0      0  
4       25        -16          0          0       1     39

In [ ]:
cols = df.select_dtypes(include = 'O').columns
cols

df = pd.get_dummies(df, columns=cols, drop_first=False)
df.head()

리뷰점수  주문개수  상품가격합계  배송비합계   총결제금액  예상_소요일수  실제_소요일수  예상대비_지연일수  예상대비_지연여부  \
0     5     1   58.90  13.29   72.19       15        7         -9          0   
1     4     1  239.90  19.93  259.83       18       16         -3          0   
2     5     1  199.00  17.87  216.87       21        7        -14          0   
3     4     1   12.99  12.79   25.78       11        6         -6          0   
4     5     1  199.90  18.14  218.04       40       25        -16          0   

   리뷰_작성지연일수  리뷰내용여부  리뷰_길이  주문상태_canceled  주문상태_delivered  고객주_AC  고객주_AL  \
0          0       1     46          False            True   False   False   
1          0       0      0          False            True   False   False   
2          0       1     90          False            True   False   False   
3          0       0      0          False            True   False   False   
4          0       1     39          False            True   False   False   

   고객주_AM  고객주_AP  고객주_BA  고객주_CE  고객주_DF  고객주_ES  고객주_GO  고객주_MA  고객주_MG  \
0   False   False   False   False   False   False   False   False   False   
1   False   False   False   False   False   False   False   False   False   
2   False   False   False   False   False   False   False   False    True   
3   False   False   False   False   False   False   False   False   False   
4   False   False   False   False   False   False   False   False   False   

   고객주_MS  고객주_MT  고객주_PA  고객주_PB  고객주_PE  고객주_PI  고객주_PR  고객주_RJ  고객주_RN  \
0   False   False   False   False   False   False   False    True   False   
1   False   False   False   False   False   False   False   False   False   
2   False   False   False   False   False   False   False   False   False   
3   False   False   False   False   False   False   False   False   False   
4   False   False   False   False   False   False   False   False   False   

   고객주_RO  고객주_RR  고객주_RS  고객주_SC  고객주_SE  고객주_SP  고객주_TO  \
0   False   False   False   False   False   False   False   
1   False   False   False   False   False    True   False   
2   False   False   False   False   False   False   False   
3   False   False   False   False   False    True   False   
4   False   False   False   False   False    True   False   

   상품카테고리_fashion_shoes  상품카테고리_가구/홈리빙/인테리어  상품카테고리_가전/전자  상품카테고리_건축/공구  \
0                 False               False         False         False   
1                 False               False         False         False   
2                 False                True         False         False   
3                 False               False         False         False   
4                 False                True         False         False   

   상품카테고리_계절/특수상품  상품카테고리_문화/취미/엔터테인먼트  상품카테고리_반려동물  상품카테고리_뷰티/헬스  \
0           False                 True        False         False   
1           False                False         True         False   
2           False                False        False         False   
3           False                False        False          True   
4           False                False        False         False   

   상품카테고리_사무/산업  상품카테고리_스포츠/레저  상품카테고리_식품/음료  상품카테고리_아기/육아/완구  \
0         False          False         False            False   
1         False          False         False            False   
2         False          False         False            False   
3         False          False         False            False   
4         False          False         False            False   

   상품카테고리_패션/의류/액세서리  
0              False  
1              False  
2              False  
3              False  
4              False

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, mean_absolute_error
from sklearn.metrics import f1_score

In [ ]:
X_tr, X_val, y_tr, y_val = train_test_split(df.drop('리뷰점수', axis = 1),
                                            df['리뷰점수'],
                                            test_size = 0.2,
                                            random_state = 2025)

In [ ]:
X_tr.shape, X_val.shape, y_tr.shape, y_val.shape

((68641, 53), (17161, 53), (68641,), (17161,))

In [ ]:
model = LinearRegression()
model.fit(X_tr, y_tr)

y_pred = model.predict(X_val)

In [ ]:
print("MSE:", mean_squared_error(y_val, y_pred))
print("R2:", r2_score(y_val, y_pred))

MSE: 1.1509265664941895
R2: 0.2537338553761934


In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, mean_absolute_error, f1_score
from collections import Counter

major = Counter(y_tr).most_common(1)[0][0]
y_pred_major = np.full_like(y_val, fill_value=major)

print("=== Majority Baseline ===")
print("Major class:", major)
print("Accuracy:", accuracy_score(y_val, y_pred_major))
print("MAE:", mean_absolute_error(y_val, y_pred_major))
print("F1 (weighted):", f1_score(y_val, y_pred_major, average="weighted"))
print("Accuracy@±1:", (np.abs(y_val - y_pred_major) <= 1).mean())

=== Majority Baseline ===
Major class: 5
Accuracy: 0.597575898840394
MAE: 0.8074121554687955
F1 (weighted): 0.44704850033617155
Accuracy@±1: 0.7972728861954431


In [ ]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(random_state = 2025)
logreg.fit(X_tr, y_tr)
y_pred_logreg = logreg.predict(X_val)

print('--Logistic--')
print("Accuracy:", accuracy_score(y_val, y_pred_logreg))
print("F1_score", f1_score(y_val, y_pred_logreg, average="weighted"))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_logreg))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state = 2025)
rf.fit(X_tr, y_tr)
y_pred_rf = rf.predict(X_val)

print('--RandomForest--')
print("Accuracy:", accuracy_score(y_val, y_pred_rf))
print("F1_score", f1_score(y_val, y_pred_rf, average="weighted"))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_rf))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


--Logistic--
Accuracy: 0.6144746809626479
F1_score 0.49174110668787896
Confusion Matrix:
 [[  525    21     0     0   932]
 [  127     4     0     1   383]
 [  167     5     0     1  1313]
 [  138     2     0     1  3286]
 [  219    21     0     0 10015]]
--RandomForest--
Accuracy: 0.6377833459588602
F1_score 0.557925080245962
Confusion Matrix:
 [[ 794    7   19   50  608]
 [  90   93    8   14  310]
 [ 111    2  128   89 1156]
 [ 109    1   24  263 3030]
 [ 193    7   51  337 9667]]


In [ ]:
# 리뷰 1~3 낮음 / 4~5 높음 / 이진분류

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_tr_bin = (y_tr >= 4).astype(int) # 4~5 높음
y_val_bin = (y_val >= 4).astype(int) # 1~3 낮음

logreg = LogisticRegression(max_iter=1000, random_state=2025)
logreg.fit(X_tr, y_tr_bin)
y_pred_logreg = logreg.predict(X_val)

print('--Logistic--')
print("Accuracy:", accuracy_score(y_val_bin, y_pred_logreg))
print("F1:", f1_score(y_val_bin, y_pred_logreg))
print("Confusion Matrix:\n", confusion_matrix(y_val_bin, y_pred_logreg))

rf = RandomForestClassifier(random_state=2025)
rf.fit(X_tr, y_tr_bin)
y_pred_rf = rf.predict(X_val)

print('--RandomForest--')
print("Accuracy:", accuracy_score(y_val_bin, y_pred_rf))
print("F1:", f1_score(y_val_bin, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_val_bin, y_pred_rf))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


--Logistic--
Accuracy: 0.8339840335644776
F1: 0.9026615190132905
Confusion Matrix:
 [[ 1102  2377]
 [  472 13210]]
--RandomForest--
Accuracy: 0.8512324456616748
F1: 0.9122469322517444
Confusion Matrix:
 [[ 1338  2141]
 [  412 13270]]


In [ ]:
 # 리뷰 1~3 낮음 / 4~5 높음 / 이진분류 / 낮은 리뷰에 가중치 추가


y_tr_bin = (y_tr >= 4).astype(int) # 4~5 높음
y_val_bin = (y_val >= 4).astype(int) # 1~3 낮음


## ***최종 모형 선택*** ##
logreg = LogisticRegression(class_weight='balanced',max_iter=1000, random_state=2025)
logreg.fit(X_tr, y_tr_bin)
y_pred_logreg = logreg.predict(X_val)

print('--Logistic--')
print("Accuracy:", accuracy_score(y_val_bin, y_pred_logreg))
print("F1:", f1_score(y_val_bin, y_pred_logreg))
print("Confusion Matrix:\n", confusion_matrix(y_val_bin, y_pred_logreg))

rf = RandomForestClassifier(class_weight='balanced',random_state=2025)
rf.fit(X_tr, y_tr_bin)
y_pred_rf = rf.predict(X_val)

print('--RandomForest--')
print("Accuracy:", accuracy_score(y_val_bin, y_pred_rf))
print("F1:", f1_score(y_val_bin, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_val_bin, y_pred_rf))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


--Logistic--
Accuracy: 0.76399976691335
F1: 0.8445416858590511
Confusion Matrix:
 [[ 2110  1369]
 [ 2681 11001]]
--RandomForest--
Accuracy: 0.8504749140492979
F1: 0.912081134790653
Confusion Matrix:
 [[ 1285  2194]
 [  372 13310]]


In [ ]:
# 리뷰 1~3 낮음 / 4~5 높음 / 이진분류 / 오버 샘플링으로 데이터 분포 맞춤

y_tr_bin  = (y_tr  >= 4).astype(int)
y_val_bin = (y_val >= 4).astype(int)

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
X_res, y_res_bin = sm.fit_resample(X_tr, y_tr_bin)

logreg = LogisticRegression(random_state=2025)
logreg.fit(X_res, y_res_bin)
y_pred_logreg = logreg.predict(X_val)

print('--Logistic--')
print("Accuracy:", accuracy_score(y_val_bin, y_pred_logreg))
print("F1:", f1_score(y_val_bin, y_pred_logreg))
print("Confusion Matrix:\n", confusion_matrix(y_val_bin, y_pred_logreg))

# RandomForest
rf = RandomForestClassifier(random_state=2025)
rf.fit(X_res, y_res_bin)
y_pred_rf = rf.predict(X_val)

rf.fit(X_res, y_res_bin)
y_pred_rf = rf.predict(X_val)

print('--RandomForest__')
print("Accuracy:", accuracy_score(y_val_bin, y_pred_rf))
print("F1:", f1_score(y_val_bin, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_val_bin, y_pred_rf))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


--Logistic--
Accuracy: 0.748849134665812
F1: 0.8386734541098967
Confusion Matrix:
 [[ 1648  1831]
 [ 2479 11203]]
--RandomForest__
Accuracy: 0.841384534700775
F1: 0.904524728165556
Confusion Matrix:
 [[ 1545  1934]
 [  788 12894]]
